### ISSUE TITLE
图片功能能否完善一些新功能

### ISSUE THREAD

**Issue by lucenli** [kisshang1993/NGA-BBS-Script#1]
感谢大佬，目前用起来很方便，但是图片浏览还是有点不那么顺手

能否增加新功能，比如图片‘上一页’‘下一页’支持键盘左右键？
或者把左右按键从屏幕下方改到图片本身左右侧？这样会更方便一些，希望考虑

**Comment by kisshang1993** [comment]
2.0版本已添加切换楼内图片的快捷键，默认为左右箭头
同时也添加了快捷键的修改功能，以防冲突
