### ISSUE TITLE
脚本功能不生效，设置面板无法打开

### ISSUE THREAD

**Issue by notgiilao** [kisshang1993/NGA-BBS-Script#105]
**描述错误信息**
脚本开启后不生效，试过刷新浏览器、重新安装、脚本自带的修复及清除缓存功能，都没有改变；
与此同时，脚本中的设置面板功能无法打开，没有跳出相应界面
同时测试了nga和178域名，也都是一致的情况
但测试您的其它脚本（护眼模式），是可以正常使用的
此外相同软件版本组合的另一台电脑上脚本可以正常使用

**复现步骤**
此问题的复现步骤:
自新电脑安装及更新相应浏览器、油猴脚本以来没正常过

**屏幕截图**
包含错误截图，F12控制台输出，配置设置信息等

**浏览器及版本号**
例如:
 - Microsoft Edge [127.0.2651.105]

**脚本管理器及版本号**
例如:
 - Tampermonkey [5.1.1]（由旧电脑浏览器同步过来）

**补充说明**
原电脑上使用正常，最近更换了电脑，重新安装浏览器和脚本后发现异常（新旧电脑软件配置相同，浏览器、油猴、脚本均为相同版本，唯一不同可能就电脑硬件配置不同以及系统版本不同，旧电脑为正版win10专业版，新电脑公司配的教育版，有做了一些组策略，具体哪些不清楚，不知道有没有影响）

**Comment by kisshang1993** [comment]
我没有复现出这个问题，按F12打开浏览器控制台，再执行相关操作，看下控制台有没有错误日志输出？

**Comment by notgiilao** [comment]
> 我没有复现出这个问题，按F12打开浏览器控制台，再执行相关操作，看下控制台有没有错误日志输出？

感谢关注，对控制台操作用法不熟悉，看了下确实很多报错，试着截了两张图，有劳帮忙查看
最后一条Uncaught TypeError: Cannot read properties of null (reading 'css')是在尝试打开设置面板时出现的

![49079617-3457-497f-8bc0-1f8f0a3881b7](https://github.com/user-attachments/assets/e8d4619d-6dd9-43de-be04-8c118afe46d4)
![48a473f6-8b1c-4073-8781-f1a1ff6ede48](https://github.com/user-attachments/assets/6d00ddf0-3b2f-415e-8afc-20dc149f073b)

**Comment by kisshang1993** [comment]
看样子是CDN引用库没有加载成功
有可能是你的网络环境或者安装了某种代理软件导致被CDN风控屏蔽掉了
检查一下是否存在这些问题？

**Comment by notgiilao** [comment]
> 看样子是CDN引用库没有加载成功 有可能是你的网络环境或者安装了某种代理软件导致被CDN风控屏蔽掉了 检查一下是否存在这些问题？

十分感谢！问题已定位，是该广告屏蔽扩展的问题：https://microsoftedge.microsoft.com/addons/detail/adblocker-ultimate/pciakllldcajllepkbbihkmfkikheffb，在该扩展中将“staticfile.net”添加到白名单后问题即可解决
