### ISSUE TITLE
查看用户活动记录按钮经常性消失，换网址也无法显示。

### ISSUE THREAD

**Issue by AoyamaT1** [kisshang1993/NGA-BBS-Script#106]
**描述错误信息**
如题。
**复现步骤**
此问题的复现步骤:
1. 打开nga，进入任意一贴
2. 查看用户活动记录按钮未出现，刷新，重启脚本均无法显示，其他功能正常。

**屏幕截图**
﻿
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/714.js? load error
715.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
6002.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
718.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
200809.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/715.js? load error
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/6002.js? load error
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/718.js? load error
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/200809.js? load error
js_commonui.js?5871329:7608 genHisLink wait
js_commonui.js?5871329:7860 init
js_commonui.js?5871329:7573 mouseover
js_commonui.js?5871329:8030 merge remote check
js_commonui.js?5871329:7866 init ok
js_commonui.js?5871329:7611 genHisLink
js_commonui.js?5871329:7573 mouseover
js_commonui.js?5871329:7575 1
js_commonui.js?5871329:7676 show call
js_commonui.js?5871329:7573 mouseover
js_commonui.js?5871329:7575 1
js_commonui.js?5871329:7676 show call
js_commonui.js?5871329:7573 mouseover
js_commonui.js?5871329:7575 1
js_commonui.js?5871329:7676 show call
js_box.js?8605181:716 push cache 0 https://nga.178.com/thread.php?fid=-447601
js_commonui.js?5871329:7879 add 二次元国家地理 -447601  undefined 1
js_commonui.js?5871329:1764 time2disload
js_default.js?9964985:446 show ad in 47 pv
js_customBg.js?111117:70 0 190 190
about:blank:1 
 
 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
about:blank:1 
 
 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
714.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/714.js? load error
718.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/718.js? load error
200808.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/200808.js? load error
js_commonui.js?5871329:7611 genHisLink
js_commonui.js?5871329:7573 mouseover
js_commonui.js?5871329:7575 1
js_commonui.js?5871329:7676 show call
js_box.js?8605181:716 push cache 1 https://nga.178.com/thread.php?fid=524
js_commonui.js?5871329:7879 add 漩涡书院 524  undefined 1
js_commonui.js?5871329:1764 time2disload
js_default.js?9964985:446 show ad in 46 pv
js_customBg.js?111117:70 0 190 190
about:blank:1 
 
 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
714.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/714.js? load error
718.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/718.js? load error
200808.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/200808.js? load error
js_box.js?8605181:716 push cache 2 https://nga.178.com/read.php?tid=41423912
js_read.js?3587937:3915 topicbtn arg set
js_bbscode_core.js?1342386:2000 
Object
js_read.js?3587937:3192 postbtn arg set
js_default.js?9964985:446 show ad in 45 pv
js_customBg.js?111117:70 0 190 190
about:blank:1 
 
 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
js_bbscode_core.js?1342386:2172 set minH 1304
js_bbscode_core.js?1342386:2177 lazy load https://img.nga.178.com/attachments/mon_202408/26/ekQ2u-h7ynK2qT1kS9g-108.jpg
NGA优化摸鱼体验.user.js:2752 NGAScript [UserEnhance]模块在[renderFormsFunc()]中运行失败！
NGA优化摸鱼体验.user.js:2585 TypeError: Cannot read properties of undefined (reading 'userInfo')
    at Object.renderFormsFunc (NGA优化摸鱼体验.user.js:6137:52)
    at HTMLTableElement.<anonymous> (NGA优化摸鱼体验.user.js:2582:58)
    at Function.each (NGA优化摸鱼体验.user.js:2:2777)
    at k.fn.init.each (NGA优化摸鱼体验.user.js:2:1419)
    at NGABBSScript.renderForms (NGA优化摸鱼体验.user.js:2576:58)
    at NGA优化摸鱼体验.user.js:2945:40
NGA优化摸鱼体验.user.js:2752 NGAScript [checkInfo]模块在[renderFormsFunc()]中运行失败！
NGA优化摸鱼体验.user.js:2585 TypeError: Cannot read properties of undefined (reading 'userInfo')
    at Proxy.renderFormsFunc (NGA优化摸鱼体验插件-信息加强.user.js:2445:52)
    at HTMLTableElement.<anonymous> (NGA优化摸鱼体验.user.js:2582:58)
    at Function.each (NGA优化摸鱼体验.user.js:2:2777)
    at k.fn.init.each (NGA优化摸鱼体验.user.js:2:1419)
    at NGABBSScript.renderForms (NGA优化摸鱼体验.user.js:2576:58)
    at NGA优化摸鱼体验.user.js:2945:40
NGA优化摸鱼体验.user.js:2752 NGAScript [UserEnhance]模块在[renderFormsFunc()]中运行失败！
NGA优化摸鱼体验.user.js:2585 TypeError: Cannot read properties of undefined (reading 'userInfo')
    at Object.renderFormsFunc (NGA优化摸鱼体验.user.js:6137:52)
    at HTMLTableElement.<anonymous> (NGA优化摸鱼体验.user.js:2582:58)
    at Function.each (NGA优化摸鱼体验.user.js:2:2777)
    at k.fn.init.each (NGA优化摸鱼体验.user.js:2:1419)
    at NGABBSScript.renderForms (NGA优化摸鱼体验.user.js:2576:58)
    at NGA优化摸鱼体验.user.js:2945:40
NGA优化摸鱼体验.user.js:2752 NGAScript [checkInfo]模块在[renderFormsFunc()]中运行失败！
NGA优化摸鱼体验.user.js:2585 TypeError: Cannot read properties of undefined (reading 'userInfo')
    at Proxy.renderFormsFunc (NGA优化摸鱼体验插件-信息加强.user.js:2445:52)
    at HTMLTableElement.<anonymous> (NGA优化摸鱼体验.user.js:2582:58)
    at Function.each (NGA优化摸鱼体验.user.js:2:2777)
    at k.fn.init.each (NGA优化摸鱼体验.user.js:2:1419)
    at NGABBSScript.renderForms (NGA优化摸鱼体验.user.js:2576:58)
    at NGA优化摸鱼体验.user.js:2945:40
js_commonui.js?5871329:1764 time2disload
714.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/714.js? load error
715.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/715.js? load error
6002.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/6002.js? load error
718.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/718.js? load error
200809.js:1 
 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM774 read.php:188 https://g1.tagtic.cn/v1/xingyou/c/200809.js? load error
Remove web limits(modified).user.js:841 

﻿

**浏览器及版本号**
例如:
 - Microsoft Edge [ 129.0.2779.0 (正式版本) dev (64 位)]

**脚本管理器及版本号**
例如:
 - 暴力猴 [2.20.0]

**补充说明**
例如安装了其他插件，或者特殊的使用环境等

**Comment by kisshang1993** [comment]
暴力猴兼容性有问题，使用篡改猴（Tampermonkey）看看

**Comment by AoyamaT1** [comment]
切换成篡改猴后也没办法显示，连带高亮楼主的功能也失效了。版本皆是最新。

控制台：﻿
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
Third-party cookie will be blocked in future Microsoft Edge versions as part of unpartitioned third-party cookie deprecation.
js_bbscode_core.js?1342386:2177 lazy load https://img.nga.178.com/attachments/mon_202408/28/axs9Q2u-70rgZaT3cSl0-sg.jpg
﻿

**Comment by kisshang1993** [comment]
无法重现问题，根据log 脚本并没有报错，是不是nga原本的js报错了
如还有问题就看看用控制变量法，能不能确定并定位到脚本的报错log，再重提此issue
