### ISSUE TITLE
公司网络封锁了cdn.staticfile.net

### ISSUE THREAD

**Issue by cyctouchfish** [kisshang1993/NGA-BBS-Script#107]
公司网络封锁了cdn.staticfile.net，有其他办法绕过它开启脚本吗

**Comment by Cyctinu** [comment]
使用自己手机wifi连接电脑一次就可以用了

**Comment by Cyctinu** [comment]
使用自己手机wifi连接电脑一次就可以用了

**Comment by 132conan** [comment]
https://github.com/staticfile/static/issues/700
staticfile已经被列入恶意网址了 @kisshang1993

**Comment by kisshang1993** [comment]
已在版本4.5.4中修复
