### ISSUE TITLE
Excel 模式下列表楼层数显示不全

### ISSUE THREAD

**Issue by CraigMChen** [kisshang1993/NGA-BBS-Script#108]
**描述错误信息**
开启 Excel 模式时，4 位数以上的高楼无法正常显示层数，只有第一个数字+省略号

**复现步骤**
开启 Excel 模式，查看列表左侧楼层数

**屏幕截图**
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/4bdc919e-d416-4e80-bbb4-fd690f1eb0f1">

**浏览器及版本号**
Chrome 128.0.6613.113 (arm64)

**脚本管理器及版本号**
 Tampermonkey [4.5.2]

**Comment by kisshang1993** [comment]
已在版本4.5.4中修复
