### ISSUE TITLE
贴内图片大小显示不正常

### ISSUE THREAD

**Issue by scythk** [kisshang1993/NGA-BBS-Script#109]
**描述错误信息**
贴内图片显示为最小，刷新页面后有概率恢复正常，开关图片缩放功能没有解决问题

**复现步骤**
此问题的复现步骤:

**屏幕截图**
![image](https://github.com/user-attachments/assets/d99071e3-4f47-4a3b-8a44-897518f9925f)
![image](https://github.com/user-attachments/assets/a4d24f5e-d7c7-40d0-9e5c-ee115403d47d)
![image](https://github.com/user-attachments/assets/8fe74eae-37c3-4f08-aebd-ce87f9d26430)

**浏览器及版本号**
Chromium 118.0.5993.159

**脚本管理器及版本号**
Tampermonkey [5.1.1]

**Comment by HonNeptune** [comment]
同样问题。可以尝试打开贴内图片缩放，然后修改高级设置中的图片缩放宽度，我这里设置的是1000

**Comment by kisshang1993** [comment]
已在版本4.5.4中修复
