### ISSUE TITLE
自动将显示附件/图片里的abc.jpg.medium.jpg/thumbs的后缀去掉

### ISSUE THREAD

**Issue by JohnChuang33** [kisshang1993/NGA-BBS-Script#18]
zsbd

**Comment by kisshang1993** [comment]
?
请详细描述

**Comment by JohnChuang33** [comment]
有些图片显示的是大/中/小的缩略图
`<img style="max-width:1992px;max-width:1992px;min-width:331px;min-height:200px;" src="https://img.nga.178.com/attachments/mon_202012/08/-7Q5-8zjgX11Za8T3cS97-5k.gif.medium.jpg" data-srclazy="" data-srcorg="https://img.nga.178.com/attachments/mon_202012/08/-7Q5-8zjgX11Za8T3cS97-5k.gif" alt="" onerror="ubbcode.imgError(this)" hld__imglist="ready">`
如上所示，有些图片是以缩略图的形式存在的
希望能有自动将缩略图展开成原图的功能，即将src中的`.medium.jpg`的后缀自动去掉

**Comment by kisshang1993** [comment]
在启用图片增强的情况下，点击图片查看大图的图片源是是使用的data-srcorg的值，即为原图
所以缩略图还是缩略图，大图查看的是原图

**Comment by JohnChuang33** [comment]
图片增强嘛，在光是浏览的情况下还可以，但如果是要用singlefile之类的扩展保存整个页面的话就不是很适用了[s:ac:哭笑]
因为有对值得一看的页面采样保存的习惯，然后每次都要手动检查去除medium.jpg的后缀挺麻烦的

**Comment by kisshang1993** [comment]
确实没有考虑到这种情况, 不过是可以加入这个功能的
这个功能已添加到更新计划, 请留意后续更新
