### ISSUE TITLE
自动翻页后刷新留在翻页最后一页

### ISSUE THREAD

**Issue by rainyuen** [kisshang1993/NGA-BBS-Script#19]
自动翻页后,再有刷新操作是不是应该回到第一页会好些?

**Comment by JohnChuang33** [comment]
这个插件的自动翻页似乎是通过自动点击nga自带的>符号按钮，所以这插件在技术上来说做不到你提到的这点，除非把自动翻页的原理改为xhr之后append到原有的table中。

**Comment by kisshang1993** [comment]
引用楼上的朋友说的，插件原理是对原来的dom做了二次处理，并没有改变其原理，翻页的同时nga也改变了url，所以你刷新页面是你当前浏览的page也是合情合理
针对这个问题，上个版本前推出了“返回顶部”功能，已解决返回第一页的问题，详请你可以看3.4的README
https://github.com/kisshang1993/NGA-BBS-Script/blob/6369c3506437ca6e57cfa3bbbef5a6cb6bbc2d48/README.md
