### ISSUE TITLE
论坛翻页后必须要刷新才能生效

### ISSUE THREAD

**Issue by lucenli** [kisshang1993/NGA-BBS-Script#2]
目前遇到几种情况下脚本会失效
1.通过nga网页的快速导航，进入对应版面后会卡在版头，必须刷新后正常浏览
2. 通过网页下方数字直接翻页后会卡在版头，刷新后正常

以上情况概率出现，请问怎么处理呢？大概就是前一阵子nga因为特殊事件重启之后开始的

**Comment by kisshang1993** [comment]
这个问题有网友反馈过，我本地测试一切正常，无法复现
你可以参考下这个问题
[https://greasyfork.org/zh-CN/forum/discussion/76874/x](https://greasyfork.org/zh-CN/forum/discussion/76874/x)
然后提供一下关键信息有助于我排查问题

**Comment by lucenli** [comment]
已回复，希望可以有帮助

**Comment by lucenli** [comment]
其实还有一个问题就是点‘编辑快捷键’会没反响，不会跳出设置快捷键的菜单
![image](https://user-images.githubusercontent.com/16946496/81254923-f762e300-905e-11ea-92d9-d950cafb61eb.png)

**Comment by kisshang1993** [comment]
已定位到问题，NGA改版缘故，功能失效，现在已经在2.3版本里修复了

**Comment by toooonyy** [comment]
chromium edge 81 +TM 上又复现了翻页 bug，FF76+violentmoneky 也一样。console log没什么信息，
![Screen Shot 2020-05-13 at 19 36 41](https://user-images.githubusercontent.com/3480434/81810258-2cb17a00-9512-11ea-8495-d6237a1b8912.png)
此时点击数字翻页多了
![Screen Shot 2020-05-13 at 19 36 49](https://user-images.githubusercontent.com/3480434/81810313-4226a400-9512-11ea-9573-4ba4ffeb3c42.png)

**Comment by kisshang1993** [comment]
> chromium edge 81 +TM 上又复现了翻页 bug，FF76+violentmoneky 也一样。console log没什么信息，
> ![Screen Shot 2020-05-13 at 19 36 41](https://user-images.githubusercontent.com/3480434/81810258-2cb17a00-9512-11ea-8495-d6237a1b8912.png)
> 此时点击数字翻页多了
> ![Screen Shot 2020-05-13 at 19 36 49](https://user-images.githubusercontent.com/3480434/81810313-4226a400-9512-11ea-9573-4ba4ffeb3c42.png)

理论的这个bug已经修复，请检查脚本是否已经升级到了最新版本
如还有问题，请新建一个issue，并且提供一下更详细的信息，例如脚本配置面板
