### ISSUE TITLE
是否考虑增加一个调整背景色的功能

### ISSUE THREAD

**Issue by visfero** [kisshang1993/NGA-BBS-Script#25]
是否考虑增加一个调整背景色的功能，类似于wps的绿色背景？
目前我在用wps使用绿色背景，看着舒服一点，如果脚步也增加调色功能，可以适应更多人的需求。
谢谢

**Comment by kisshang1993** [comment]
计划添加一个配色方案功能，会包含更改背景颜色，请留意后续更新内容

**Comment by landuo** [comment]
支持这个想法，这背景太不像摸鱼了:(
