### ISSUE TITLE
仅显示X赞以上回复的功能

### ISSUE THREAD

**Issue by Wighthiul** [kisshang1993/NGA-BBS-Script#29]
有些主题含有大量的灌水楼层，如果能够实现一个仅显示X赞（可自定义）以上回复功能，或许可以强化冲浪体验。

我遇到的困难：

1. NGA的API只能按页（20楼）读取，无法返回一个包含所有回复的列表。

   可能的解决方案：先一页一页请求所有回复，再进行精选。

2. 从API获得的数据为JSON格式，无法直接作为html嵌入。

   可能的解决方案：先记录所有精选回复的pid，再通过对read.php同时请求tid和pid的方式获得该回复的html（每个楼层都是一个\<table\>），最后把所有的精选回复串起来。

3. 如果前两条能够克服，还要限定每页显示的精选回复最大条数。

可能的捷径：NGA自带选择四条最高赞回复的功能。如果该功能来自前端而非数据库端，或可更简单地得到高赞回复。

一个更简单但稍差一点的实现是，直接屏蔽所有低赞回复 X )

> 不过事实上我对油猴和JS都不是很了解 [扇子笑] 在此只是提出一个想法

**Comment by kisshang1993** [comment]
本脚本跟你说的原理不一样

脚本的工作原理是后处理，也就是说是在原有的页面之上，解析数据并通过操作dom来更改某些事物

并不是直接使用API获取的，也就是说，脚本目前的工作原理是，只能处理分析页面上存在的，页面没有的东西是不能处理的
