### ISSUE TITLE
翻页bug

### ISSUE THREAD

**Issue by toooonyy** [kisshang1993/NGA-BBS-Script#3]
~~测试环境 chromium edge 81+TM4.10 和 FF76+VM2.12.7，脚本均是 2.5 版，使用以下配置
截图的log开了，
edge+TM
点开帖子
![Screen Shot 2020-05-14 at 10 04 34](https://user-images.githubusercontent.com/3480434/81884447-78523b00-9587-11ea-97b7-0221037de49c.png)~~
----
最新的 commit 8edb8dc 修复了乱注入Excel CSS 的问题，TM 下脚本正常工作。但用VM，翻页时会有两种报错（edge）
 1. `getElementsByTagName is not a function`
 1. `Cannot read property 'nextSibling' of undefined`
![Screen Shot 2020-05-14 at 10 22 36](https://user-images.githubusercontent.com/3480434/81885531-0f1ff700-958a-11ea-9607-28b6b7356650.png)

然后论坛自己CSS就没了，
![Screen Shot 2020-05-14 at 10 23 13](https://user-images.githubusercontent.com/3480434/81885638-4b535780-958a-11ea-960f-e47d60162934.png)

 如果需要完整log我可以上传

**Comment by kisshang1993** [comment]
根据LOG观察，这两个函数实在NGA自己的js_commonui.js下报的错，或许NGA的自己的脚本错误？
另外同等测试条件下我并没有出现问题，脚本都是能够正常运行

**Comment by toooonyy** [comment]
> 根据LOG观察，这两个函数实在NGA自己的js_commonui.js下报的错，或许NGA的自己的脚本错误？
> 另外同等测试条件下我并没有出现问题，脚本都是能够正常运行

稍微研究了一下加了一行 
`// @inject-into content`就好了，似乎VM默认是 page。

**Comment by kisshang1993** [comment]
确实是因为引用JQuery库直接注入到了page里跟NGA自带的$起了冲突，后续版本我会加入META里以解决这个问题
