### ISSUE TITLE
关闭NGA Ajax功能

### ISSUE THREAD

**Issue by MikeZTM** [kisshang1993/NGA-BBS-Script#30]
由于NGA翻页Ajax和adblock/ublock冲突, 希望能提供一个完全关闭ajax功能的选项.

我自己目前在使用以下代码来规避Ajax:

`window.addEventListener('click', function (event) {
        event.stopPropagation();
    }, true);`

当然也希望能找到更好的解决翻页白屏的办法.

**Comment by kisshang1993** [comment]
完全屏蔽ajax不现实，本质上nga是基于ajax来更新数据的，这样会导致每次都会重载页面

如果是与浏览器广告插件冲突，可以尝试使用本地流量代理插件

另外翻页白屏是什么原因导致的？这部分可以具体反馈一下

**Comment by MikeZTM** [comment]
https://img4.nga.178.com/common_res/js_box.js

P.showNew 函数在http 200回调执行时会造成白屏(NGA黄色背景, 3/4进度条), HTML没有被正确写入. 摸鱼插件提示tagtic.cn相关错误.

配置: Microsoft Edge 89.0.774.57  ublock origin + Easylist(China)

**Comment by kisshang1993** [comment]
这显而易见就是NGA自身的问题了，这并不在脚本的工作范畴之内，你可以去论坛开发板块提交网站bug（哭笑
