### ISSUE TITLE
希望excel页面上的加入搜索功能

### ISSUE THREAD

**Issue by kpas8288** [kisshang1993/NGA-BBS-Script#31]
每次搜个东西还需要切换回去 不是很方便
希望把页面原来的搜索功能挪到这个地方 正好利用这个图标

![image](https://user-images.githubusercontent.com/42954645/112408631-20619480-8d53-11eb-8541-cb3bcede0258.png)

**Comment by kpas8288** [comment]
简单挪动了一下 有点丑
期望作者优化

![image](https://user-images.githubusercontent.com/42954645/112413622-7b978500-8d5b-11eb-9409-4c1395481d1d.png)

**Comment by kisshang1993** [comment]
已经在3.8.0版本中将整个菜单栏都移过去了，如下图
![WPS风格预览](https://i.loli.net/2021/03/31/VNRQibFS6Mas9dy.png)
