### ISSUE TITLE
希望能屏蔽页面内的广告

### ISSUE THREAD

**Issue by amor33** [kisshang1993/NGA-BBS-Script#32]
毕竟是摸鱼模式。。中间还带广告太违和了

![微信截图_20210325132833](https://user-images.githubusercontent.com/20469760/112424221-059d1900-8d6f-11eb-9bdb-42bb45ae585c.png)
![微信截图_20210325133419](https://user-images.githubusercontent.com/20469760/112424252-1057ae00-8d6f-11eb-9fed-4f8bc7a1da8b.png)

**Comment by kisshang1993** [comment]
此功能从脚本实用性的角度来考虑，是没必要的
现阶段屏蔽广告都是使用各种屏蔽广告插件，Adblock等等，术业有专攻
一方面是脚本屏蔽广告效果较差，另一方面屏蔽规则需要时常更新，对于脚本来说并不适用
所以短期内不会有广告过滤功能的开发计划
