### ISSUE TITLE
隐藏头像功能有时候会失效

### ISSUE THREAD

**Issue by gecan123** [kisshang1993/NGA-BBS-Script#33]
当前插件版本:v3.7.2
默认开启了[隐藏头像], 大部分时间也是正常不显示的
小概率刷新/进帖后头像会正常展示, 需要手动按q再隐藏下, 发生了不少次

**Comment by kisshang1993** [comment]
观察一下是否只有隐藏头像功能失效，还是在当前页面整个脚本都失效
另外请在提供一下浏览器等信息

**Comment by gecan123** [comment]
> 观察一下是否只有隐藏头像功能失效，还是在当前页面整个脚本都失效
> 另外请在提供一下浏览器等信息

只有隐藏头像功能失效, 其余功能如 excel/隐藏图片 等都正常运作
浏览器使用的是360极速13.0, 官网信息用的是chromium86内核
油猴扩展运行于AdGuard7.5.3, 方便多浏览器使用

以前这套配置跑了有一年了吧, 之前版本的头像没出过问题
忘记从哪个版本开始这个问题, 但是应该持续了有一个月左右

**Comment by kisshang1993** [comment]
我在相同的环境内并没有复现出这个bug
推论可能由以下原因：
1. 第三方脚本或者浏览器插件类的冲突
2. 设置差异

建议再继续测试，开启F12控制台，复现BUG查看有无报错信息
或者使用浏览器脚本管理器运行脚本测试一下有无此问题

**Comment by gecan123** [comment]
![sc2](https://user-images.githubusercontent.com/33063205/113077504-dd486b00-9203-11eb-9570-b1da77172c15.jpg)
![sc1](https://user-images.githubusercontent.com/33063205/113077508-de799800-9203-11eb-8015-4869a80db32e.jpg)
这个情况出现的概率不大, 刷一个小时可能一次或者没有
这次碰到的情况如图, 其他功能正常, 头像隐藏失效

**Comment by kisshang1993** [comment]
太难以复现了，先看看有无规律，这种BUG很难定位

**Comment by gecan123** [comment]
又经过几天的使用, 捕捉到一些规律
1. 大概率首次打开nga帖子时, 会出现这种场景
2. 不仅头像会显示, 表情图片也会显示(之前很多帖子没有图片表情, 就没注意到), 我发的上一张图中, 1L的表情也显示出来了
3. 刷新后一段时间就不会有问题了

大概率是加载慢导致的? 有时候加载慢, 头部的excel部分也会显示类似`这是一张excel图片`之类的文本, 约1s后加载成功便恢复正常excel样式

**Comment by kisshang1993** [comment]
已定位到此问题，原因是NGA的脚本可能因为网络的原因极低的概率渲染在本脚本的后面
现已在3.8.0版本里针对性的解决了问题
