### ISSUE TITLE
2020.04.10 仿造Excel的图片不显示

### ISSUE THREAD

**Issue by babyhux** [kisshang1993/NGA-BBS-Script#34]
【这里应该是一张仿造Excel的图片，如不显示，请刷新重试，如还不显示，请及时反馈！】
是我个人问题吗

**Comment by kisshang1993** [comment]
多刷新几次还是不显示吗？

**Comment by w2131978** [comment]
同样问题+1
直接访问https://i.loli.net/2021/04/07/xwTM4FiZdAb7u8j.png 也上不了，似乎是图床抽了

**Comment by kisshang1993** [comment]
现在直接用base64，应该没问题了

**Comment by babyhux** [comment]
好耶 更新到3.8.1就能继续快乐摸鱼了
谢谢
