### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by Chunbear** [kisshang1993/NGA-BBS-Script#35]
很感谢大佬能开发一个这样的脚本！！谢谢！
然后是使用中的一些小问题，第一个就是手动翻页以及直接修改地址栏页码的时候后楼主不会标红了！不知道这个能不能解决。第二个自动翻页可不可以加上一个按住某个键先暂停自动翻页的功能呢！因为有些帖子好几百页....或者直接加一个跳转到某页的选项。
再次感谢！

**Comment by kisshang1993** [comment]
手动翻页改页码不会标记确实是个BUG，这个将会在下个小版本修复
至于跳转某页功能...这是NGA本身就有的功能，如果需要临时手动跳转一下，可以用顶部的的页码栏来操作

**Comment by Chunbear** [comment]
Excel主题模式是不是只有最下面有翻页？上面没找到...开了自动翻页的话到下面就会自动下一页点不到了。

**Comment by kisshang1993** [comment]
可以使用Excel切换的快捷键，默认R来切换到普通页面使用
脚本已更新到3.9.5，上述问题已经修复
