### ISSUE TITLE
2.5版本点进帖子会自动变成excel模式，返回上级也是excel模式，必须重新刷新。

### ISSUE THREAD

**Issue by Caponia** [kisshang1993/NGA-BBS-Script#4]
TM版本4.1
同时启用的只有这一个脚本。 
![FireShot Capture 013 - 艾欧泽亚 NGA玩家社区 P1 - nga 178 com](https://user-images.githubusercontent.com/33995465/82016200-10990e80-96b3-11ea-99cb-b6b1110bc86d.png)
![FireShot Capture 014 - 工作簿1 - nga 178 com](https://user-images.githubusercontent.com/33995465/82016218-1bec3a00-96b3-11ea-90c6-2db8eaf8f90f.png)
![FireShot Capture 015 - 工作簿1 - nga 178 com](https://user-images.githubusercontent.com/33995465/82016245-2d354680-96b3-11ea-875b-ea3c1ddaaf0b.png)
![FireShot Capture 018 - 艾欧泽亚 NGA玩家社区 - nga 178 com](https://user-images.githubusercontent.com/33995465/82016250-2f97a080-96b3-11ea-8b57-8098dfa57c24.png)

**Comment by kisshang1993** [comment]
这个BUG已经在https://github.com/kisshang1993/NGA-BBS-Script/commit/8edb8dc5417b5a0f07113896c6a89c5eb7834bec 后修复，重新安装一下脚本即可
