### ISSUE TITLE
修改字体后，设置界面无法显示完全

### ISSUE THREAD

**Issue by GatherStar** [kisshang1993/NGA-BBS-Script#42]
![image](https://user-images.githubusercontent.com/50571479/130352413-904a5dc1-1ab2-4452-a064-8f91d92d14f3.png)

![image](https://user-images.githubusercontent.com/50571479/130352428-7f57afdd-2a29-42bf-91fe-4979f9164333.png)

**Comment by kisshang1993** [comment]
安装最新版本之后看下还有无此问题，如还有就附带更详细的配置及截图等重新提个issue
