### ISSUE TITLE
在新标签页打开的bug

### ISSUE THREAD

**Issue by toooonyy** [kisshang1993/NGA-BBS-Script#5]
开启这个功能以后，点在搜索页面的帖子会打开两个页面，其中一个真的叫`javascript:void(0)`，估计是
`<a href="javascript:void(0)" id="t_tt10_18" class="topic" target="_blank"></a>`比正常版面多了 target 引起的

**Comment by kisshang1993** [comment]
VM兼容性问题，已经在2.6版本修复
