### ISSUE TITLE
excel左侧序号会在回帖后消失 4.0复现

### ISSUE THREAD

**Issue by kpas8288** [kisshang1993/NGA-BBS-Script#50]
配置如下
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/42954645/e2848190-162b-4d0c-b0cf-c0a2631dc436)

1.进入版面 第一列正常显示为回复数
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/42954645/ba77146b-951a-45ce-8b89-05bf034f6b65)
2.进入任意帖子 点击"发表回复"  回复一条帖子
3.回复完毕后点击导航栏的版面连接
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/42954645/23d5e7b6-ac1b-4e2e-80f5-c3bfec8d6d4c)
4.回到版面 第一列为顺序(期望为回复数)
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/42954645/c21699bc-314a-4fc6-89e4-4b45695b2162)

**Comment by kisshang1993** [comment]
仍未能复现出此问题，推送了4.1的更新，对可能导致此问题的地方做了修改，尝试下还有没有此问题

**Comment by kpas8288** [comment]
4.1没有复现
