### ISSUE TITLE
用户增强模块不生效

### ISSUE THREAD

**Issue by willme0** [kisshang1993/NGA-BBS-Script#54]
火狐115.0.1 (64 位)
脚本4.2.0
访问bbs.nga.cn 
控制台输出：
![2023-07-08_150247](https://github.com/kisshang1993/NGA-BBS-Script/assets/22152849/2275de47-d804-4d75-8e9f-ae70b4db9209)

**Comment by kisshang1993** [comment]
已推送版本v4.2.1，修复了此问题
