### ISSUE TITLE
查成分的逻辑有问题

### ISSUE THREAD

**Issue by snyssss** [kisshang1993/NGA-BBS-Script#57]
使用parent里的name会导致冲水或者删除后不会进行统计。
应该跟属地一样写一个类似的版面索引，然后匹配数据里的fid。
或者更简单一点，保留当前的获取方式，但是判断帖子冲水的时候，再根据fid在索引里匹配常用版面，目前把水区、国新区，还有银色黎明的垃圾回收区加进去应该就可以包含绝大多数情况。
文字描述也应该调整一下，说明是最近活跃记录，毕竟只查了前几页。

**Comment by kisshang1993** [comment]
想法一致，在4.2.2已经调整了这部分统计方式，现在冲水掉的记录也统计在内
后续功能看看怎么优化吧，毕竟现在只是图一乐，精准统计代价还是挺大的- -
