### ISSUE TITLE
从主题列表点击打开帖子内容页能否直接按EXCEL模式显示？

### ISSUE THREAD

**Issue by greedygod** [kisshang1993/NGA-BBS-Script#6]
已开启excel模式浏览。
现在点进去阅读帖子的时候会先载入原论坛界面的，稍微等一两秒才渲染变成表格模式，容易露馅。

之前用的另一个https://greasyfork.org/zh-CN/scripts/40576-nga-excel 没有这个问题

**Comment by kisshang1993** [comment]
仔细观察一下，都是一样的，由于机制问题，都会先载入原来的界面，然后再进行二次渲染
建议使用excel功能时取消新页面打开链接功能，可以提高使用体验
