### ISSUE TITLE
页面内广告图片

### ISSUE THREAD

**Issue by DrWangTeleCom** [kisshang1993/NGA-BBS-Script#63]
**需求建议**
版头、帖内横向插入、纵向漂浮的广告图片可否在excel模式下隐藏，对摸鱼行为影响较大
**参考案例**
暂无

**补充说明**
暂无其他补充

**Comment by kisshang1993** [comment]
广告屏蔽非本脚本的功能范围，建议使用浏览器插件 ADGuard或ADBlock，清爽的很
