### ISSUE TITLE
[userEnhance]模块在[renderFormsFunc()]中运行失败

### ISSUE THREAD

**Issue by panasalik** [kisshang1993/NGA-BBS-Script#64]
**描述错误信息**
缺少用户增强面板。

**复现步骤**
无

**屏幕截图**
<img width="167" alt="image" src="https://github.com/kisshang1993/NGA-BBS-Script/assets/41010197/7e030473-8510-4329-bf08-cb46b6de3415">

**Console Log**
<img width="420" alt="image" src="https://github.com/kisshang1993/NGA-BBS-Script/assets/41010197/f8c94d8b-2d71-4c8c-bec9-510637cb9752">

**System Info**
- Windows 11 Pro 22H2 Build 22621.2134
- Chrome Version 116.0.5845.96 (Official Build) (64-bit)
- Violentmonkey 2.15.0

**补充说明**
已在 Incognito mode 复现，仅开启 Violentmonkey。

**Comment by kisshang1993** [comment]
脚本引用了些脚本管理器的特性，暴力猴兼容性一直是有点问题的
尝试下此问题是否有在其他脚本管理器出现？比如TamperMonkey？

**Comment by panasalik** [comment]
> 脚本引用了些脚本管理器的特性，暴力猴兼容性一直是有点问题的 尝试下此问题是否有在其他脚本管理器出现？比如TamperMonkey？

TamperMonkey 使用正常，确定是 Violentmonkey 不兼容，感谢。
