### ISSUE TITLE
NGA更新了新域名

### ISSUE THREAD

**Issue by DragonBreast** [kisshang1993/NGA-BBS-Script#65]
新域名：https://g.nga.cn/

**Comment by DragonBreast** [comment]
点进 https://bbs.nga.cn 的链接后，会跳转至该域名，并导致插件失效

**Comment by kisshang1993** [comment]
经测试[bbs.nga.cn](https://bbs.nga.cn/)并没有重定向至https://g.nga.cn/，看看是不是你有其他的插件或脚本影响到了跳转

**Comment by DragonBreast** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DragonBreast** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
