### ISSUE TITLE
隐藏版头在收藏页面会把收藏夹也隐藏掉

### ISSUE THREAD

**Issue by 1nj0k** [kisshang1993/NGA-BBS-Script#66]
**描述错误信息**
开启隐藏版头后，会把收藏夹页面的文件名隐藏掉

**复现步骤**
此问题的复现步骤:
1. 进入 https://bbs.nga.cn/thread.php?favor=1
2. 如果开启隐藏版头功能，则无法显示收藏夹

**屏幕截图**
包含错误截图，F12控制台输出，配置设置信息等
1. 开启功能
![Screenshot_20230824_093915](https://github.com/kisshang1993/NGA-BBS-Script/assets/13143916/8487c698-8843-4cdf-80f3-a40be73b96ea)

2. 关闭功能
![Screenshot_20230824_093947](https://github.com/kisshang1993/NGA-BBS-Script/assets/13143916/11ae7075-aac5-4158-bc26-442719521866)

**浏览器及版本号**
例如:
 - Firefox [117]

**脚本管理器及版本号**
例如:
 - Tampermonkey [4.19.0]

**补充说明**
例如安装了其他插件，或者特殊的使用环境等

**Comment by kisshang1993** [comment]
已在4.2.5中修复此问题
