### ISSUE TITLE
用户增强功能修复

### ISSUE THREAD

**Issue by toooonyy** [kisshang1993/NGA-BBS-Script#68]
**描述错误信息**
related https://github.com/kisshang1993/NGA-BBS-Script/issues/67 和 https://github.com/kisshang1993/NGA-BBS-Script/issues/64 ，可能是一个violentmonkey上用户增强上功能的一个dirty fix/workaround。

**复现步骤**
把 [// @inject-into  content](https://github.com/kisshang1993/NGA-BBS-Script/blob/8a1e6c93a7c39af9d6fbabc2dde72f78027adb4f/Script.js#L19) 这个改成 page

**屏幕截图**
<img width="1101" alt="Screen Shot 2023-09-18 at 10 56 32" src="https://github.com/kisshang1993/NGA-BBS-Script/assets/3480434/b375011b-bdeb-401a-8573-09a787952241">

**浏览器及版本号**
 - Firefox ESR [115.2.1] 

**脚本管理器及版本号**
 - Violentmonkey 2.15.0

**补充说明**
没有提PR因为不知道会不会破坏 Tampermonkey/chromium 系。目前来看脚本正常运行。

**Comment by La-Hire** [comment]
确实可以，不过暴力猴可以手动设置覆盖掉，脚本页面，</>设置，设置页面，注入模式 默认改成page

**Comment by jqtmviyu** [comment]
![图片](https://github.com/kisshang1993/NGA-BBS-Script/assets/19925192/7d0e5891-4d95-4fb8-9aca-96959f9bca7d)

**Comment by toooonyy** [comment]
确实可以自行设置，关闭了吧
