### ISSUE TITLE
希望添加长备注的功能

### ISSUE THREAD

**Issue by XDcedar** [kisshang1993/NGA-BBS-Script#69]
**需求建议**
目前的备注是标签形式，感觉不太方便。我写备注习惯写长备注，会添加一些参考链接等，这样方便我回忆当时的想法。
打标签的形式无法满足这样的需求，时间长了之后忘了自己当时为何打这个标签，反而容易造成误解。因此希望能提供长备注功能，能更自由和完整地记录备注。

**参考案例**
暂无。biliscope也许算是一个参考？

**补充说明**
希望备注不要直接显示，最好是点击按钮或触发快捷键展开后再读取。
并且最好支持导入导出，最好是使用JSON等可阅读和修改的格式。

**Comment by kisshang1993** [comment]
标记功能后续版本会有一个结构上的调整，届时会添加此功能

**Comment by XDcedar** [comment]
我发现现在的标签功能好像因为没有使用 `GM_` 的函数，所以无法跟 Tampermonkey 一起导出？本来我想的是利用 Tampermonkey 的导出功能转移备注，这样就没必要支持导入导出功能了，但现在看来还是需要加上这个功能的..

**Comment by kisshang1993** [comment]
原本数据是储存在localstorage中，使用过程中我发现一些用户有可能会不小心把本地储存给删掉了，导致配置丢失
后续将会把所有配置储存换到indexdb中或leveldb中
本身标签数据是以JSON储存的，导出是方便传输base64加密了一下，解密后可以直接修改的

**Comment by XDcedar** [comment]
真的是为了方便传输么，JSON本身就是方便传输的格式吧？

**Comment by kisshang1993** [comment]
最新的v4.4版本已添加上述功能
