### ISSUE TITLE
提个小需求

### ISSUE THREAD

**Issue by kpas8288** [kisshang1993/NGA-BBS-Script#7]
现在第一列是1234567的序号(其实没什么卵用)
希望第一列改为原来的论坛功能(显示本帖回复数量,点击弹出新窗口)

也可以做成配置

**Comment by kisshang1993** [comment]
现阶段对于excel单独这一个功能没有必要单独添加更多的配置，会看起来臃肿
至于这个提议我先记录下来，后续看看会如何用一个比较合适的方法来兼容这个提议

**Comment by kisshang1993** [comment]
此功能已在2.7版本中的高级设置中可以设置
