### ISSUE TITLE
点击两次图片 图片会消失

### ISSUE THREAD

**Issue by wantMeat** [kisshang1993/NGA-BBS-Script#71]
打开插件后哪怕不开启任何功能,在点击某些图片后第一张图片 src就不见了

好像是src结尾为".jpg.medium.jpg"的基本都会出现问题
测试帖子:
https://bbs.nga.cn/read.php?tid=38414458&_fp=2
https://bbs.nga.cn/read.php?tid=38259986
https://bbs.nga.cn/read.php?tid=38410245&_fp=2

**Comment by kisshang1993** [comment]
提供下前后对比效果截图吧，我这边未能复现出描述的问题

**Comment by Pual397** [comment]
![图片](https://github.com/ktiezng1993/NGA-BBS-Script/assets/65188426/718479a0-a6cc-481f-bc1c-117dd290d680)
测试帖子https://bbs.nga.cn/read.php?tid=38483461
演示里3张图 前两张第二次开启会消失，第三张不会
与题主相反的是，消失的两张src后缀.JPG 不会消失的第三张src后缀.jpg.medium.jpg

**Comment by kisshang1993** [comment]
此问题已定位，已在v4.4.1中修复
