### ISSUE TITLE
坚果云，WebDAV请求失败! 状态码: 404

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [kisshang1993/NGA-BBS-Script#72]
**描述错误信息**
检查链接显示：连接成功！同步配置看起来没问题
但上传配置显示：WebDAV请求失败! 状态码: 404
下载最新配置显示：WebDAV请求失败! 状态码: 400

**浏览器及版本号**
Chrome 版本 118.0.5993.120

**脚本管理器及版本号**
 - Tampermonkey [5.0.6189]

**Comment by kisshang1993** [comment]
坚果云是不能直接在根目录上传文件的，你需要自己创建一个文件夹，例如`NGA-BBS-Script`
那么webdav的地址即为：`https://dav.jianguoyun.com/dav/NGA-BBS-Script` 即可正常使用
