### ISSUE TITLE
网事杂谈首页会展示版主置顶的广告贴

### ISSUE THREAD

**Issue by dz2008hqw** [kisshang1993/NGA-BBS-Script#73]
**描述错误信息**
网事杂谈首页会展示版主置顶的广告贴

**屏幕截图**
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/11754782/7894c6dc-879e-4173-aa61-b430e6a2497a)

**浏览器及版本号**
最新版 Chrome

**脚本管理器及版本号**
 - Tampermonkey [4.19.0]

**Comment by kisshang1993** [comment]
这种展示广告贴的只需要屏蔽掉该发帖用户即可
