### ISSUE TITLE
Firefox无法更改/保存设置

### ISSUE THREAD

**Issue by Pual397** [kisshang1993/NGA-BBS-Script#74]
**描述错误信息**
 - windows10火狐最新版无法更改/保存设置，也不能弹出高级模式/快捷键等窗口，插件管理弹出后无法关闭。

**复现步骤**
 - 全新安装就不行

**屏幕截图**
GIF图展示了相关错误信息
![2023-11-21 14-39-42](https://github.com/kisshang1993/NGA-BBS-Script/assets/65188426/7debf3f6-175b-488c-a79e-8783d6f608bd)

**浏览器及版本号**
 - Firefox [119.0.1 (64 位)]

**脚本管理器及版本号**
 - Tampermonkey [4.19.0]

**补充说明**
 - 全新安装的firefox。有UBLOCK ORIGIN，关闭UBO功能后问题依旧，应该不是UBO引起的。

**Comment by kisshang1993** [comment]
提供一下F12控制台日志，可能有报错信息

**Comment by Pual397** [comment]
不知道是不是这个
ReferenceError: script_muti_get_var_store is not defined
![图片](https://github.com/kisshang1993/NGA-BBS-Script/assets/65188426/d2c8a2e9-dea5-4f57-8e5f-fc89d941a340)

**Comment by kisshang1993** [comment]
那个不是脚本的错误，尝试按以下步骤重试一下看能不能捕获到错误：

1. 先开启F12控制台
2. 重新点击下异常的按钮
3. 查看控制台有没有捕获到错误输出

**Comment by Pual397** [comment]
没有，控制台没有任何更新/提示

**Comment by akb21** [comment]
firefox 120同样的错误。不知道下面这个是不是错误输出。点击按钮的时候控制台是没有输出的。
![图片](https://github.com/kisshang1993/NGA-BBS-Script/assets/44021228/79fd7412-a3a9-4809-bc7e-3b2dc6cac422)

**Comment by Pual397** [comment]
突然发现正常了，可能是火狐更新了吧。当前插件的浏览历史还是不能用，但我觉得已经够用了。
