### ISSUE TITLE
错误地标记“楼主”

### ISSUE THREAD

**Issue by lengyanyu258** [kisshang1993/NGA-BBS-Script#76]
**描述错误信息**

在查看自己单独的回复后会将自己标记为“楼主”
然后点击进帖子又会将真正的楼主标记出来
然而此时却会显示出两个楼主（真正的楼主、自己）

**复现步骤**

此问题的复现步骤:
1. 点击“我的回复”查看“用户发布的贴子”
2. 点击 `[在主题中的回复]`
3. 点击该贴子进行浏览

**屏幕截图**

![screenshot20231204](https://github.com/kisshang1993/NGA-BBS-Script/assets/15699793/e02e045a-4354-47f3-a681-f57b2e1693aa)

**脚本管理器及版本号**

 - NGA优化摸鱼体验 4.4.1

**Comment by kisshang1993** [comment]
感谢反馈，此问题已在4.4.2中修复
