### ISSUE TITLE
WebDAV配置无法同步

### ISSUE THREAD

**Issue by zhn-1024** [kisshang1993/NGA-BBS-Script#77]
使用的坚果云  检查链接没有问题  但是无法上传

![微信图片_20231214115434](https://github.com/kisshang1993/NGA-BBS-Script/assets/58942428/b49a2dbc-5abd-48d2-988d-e078f7445737)
![微信图片_20231214115441](https://github.com/kisshang1993/NGA-BBS-Script/assets/58942428/5aebe8b4-a33a-4a76-9fc6-f19b462f77cb)

**Comment by xiaoyuruoxuan** [comment]
参考这个https://content.jianguoyun.com/3980.html

测试成功了。

**Comment by kisshang1993** [comment]
#72 合并问题
