### ISSUE TITLE
改进Tag

### ISSUE THREAD

**Issue by Mastize** [kisshang1993/NGA-BBS-Script#8]
当前tag功能为灰色小字，不易阅读
下图为该脚本和另一款脚本NGA filter的tag功能对比，另一款明显更加清晰
希望至少改进下tag的字体颜色和大小

![捕获](https://user-images.githubusercontent.com/17522169/88459336-33bc1780-cec7-11ea-9b64-e74ef611dae1.PNG)

**Comment by kisshang1993** [comment]
已更新至3.0，欢迎抓虫
