### ISSUE TITLE
excel皮肤模式未展示表情包

### ISSUE THREAD

**Issue by jokerElsa** [kisshang1993/NGA-BBS-Script#80]
**描述错误信息**
excel皮肤模式未展示表情包
抱歉开个issue，issue里和自述里好像没看到相关问题。

**复现步骤**
此问题的复现步骤:
1. 开启皮肤模式，使用腾讯文档
2. 勾选隐藏表情是可以展示类似，[呆]。
3. 不勾选则是空白（附截图）不过长按拖拽表情是能看到的
4. 重启浏览器，插件的修复选项已尝试

**屏幕截图**
包含错误截图，F12控制台输出，配置设置信息等
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/26356408/306a8728-47e3-48de-925a-156b6a8e5a55)

**浏览器及版本号**
Chrome 120.0.6099.110（正式版本） （64 位）

**脚本管理器及版本号**
例如:
 - Tampermonkey [5.0.0]

**补充说明**
例如安装了其他插件，或者特殊的使用环境等

**Comment by kisshang1993** [comment]
暂未复现出此bug，可否提供一下可以稳定复现出此bug的URL以供排查问题

**Comment by jokerElsa** [comment]
我这边是必现，现在的版本是122.0.6261.70（正式版本） （64 位）
油猴是5.0.1
脚本是4.4.1

**Comment by kisshang1993** [comment]
暂先关闭，如后续有稳定复现通道可以重提此issue
