### ISSUE TITLE
[BUG]折叠过长引用功能出现错误

### ISSUE THREAD

**Issue by frostylight** [kisshang1993/NGA-BBS-Script#81]
开启折叠过长引用功能时，有时折叠会出现错误
使用修复脚本无法修复
未登录nga账号

 - nga脚本 [4.4.1]
 - firefox [121.0] 
 - Tampermonkey [5.0.0]

![图片](https://github.com/kisshang1993/NGA-BBS-Script/assets/31412334/d30e293e-5260-40d3-88f1-a303843c4415)
https://nga.178.com/read.php?tid=37098191&_fp=3&page=90&rand=286

* 可能原因
在一楼内存在多个quote引用时，触发了折叠过长引用，为多个引用都添加了class“hld__quote-fold"，当展开折叠时，只有触发的hld__quote-box删除了自身，但是将一楼内所有引用的“hld__quote-fold"都删除，导致其他未删除的hld__quote-box显示错误

* 期望结果
问题应该是未考虑到某些情况下用quote排版导致一楼内存在多个quote的情况，希望一楼内的不同quote分开折叠

**Comment by frostylight** [comment]
尝试修复了一下，看上去可行
![图片](https://github.com/kisshang1993/NGA-BBS-Script/assets/31412334/d60842cc-421a-405c-b3f4-bfc5b8af596c)

**Comment by kisshang1993** [comment]
暂未复现出此bug，可否再提供一个可以稳定复现出此bug的URL？

**Comment by frostylight** [comment]
> > 暂未复现出此bug，可否再提供一个可以稳定复现出此bug的URL？
> 
> 我刚试了一下，4.4.2依旧可以在该帖1781楼复现 效果大致是1781楼同一楼两个引用都被折叠，在展开（查看全部）任意一个后 第一个引用块内会出现如issue截图内的BUG
> 
> 感觉适当调低 高级设置-自动折叠引用高度 可能更容易触发这个BUG

又测试了一下，BUG不是出现在第一个引用块位置，而是在整个页面偏上比较接近顶部的位置。只是刚好这页这个位置有个引用

**Comment by kisshang1993** [comment]
确认问题，已在4.4.3中修复
