### ISSUE TITLE
“用户增强”模块在暴力猴下不可用

### ISSUE THREAD

**Issue by Huiwen-Zuo** [kisshang1993/NGA-BBS-Script#83]
**描述错误信息**
“用户增强”模块在暴力猴下不可用

**复现步骤**
使用暴力猴安装后，大部分功能均可运行，但用户增强模块会在控制台报错“unsafeWindow.commonui is undefined”，表现为没有额外的信息显示在用户信息栏。
取消“用户增强”功能的勾选后此报错消失。
其他有关用户信息栏的功能可正常运行（比如标签）。

**屏幕截图**
![NGAScript](https://github.com/kisshang1993/NGA-BBS-Script/assets/79953320/5f4dac7d-a7f9-44d0-beab-b46c106b090a)

**浏览器及版本号**
 - Firefox [121.0.1]

**脚本管理器及版本号**
 - Violentmonkey[2.18.10] （出现前述bug）
 - Tampermonkey[5.0.1] （能够正常运行）

**补充说明**
因为我平时都是用暴力猴，如果作者有时间check一下这个问题就再好不过了，提前感谢。

**Comment by lifegpc** [comment]
测试了下，应该是暴力猴没有正确实现unsafeWindow的问题，尝试改成 `@inject-into  page` window依旧处于沙箱环境内。这应该是扩展的问题

**Comment by kisshang1993** [comment]
unsafeWindow是核心api，目前除了篡改猴之外其他的管理器多少有点兼容性问题，所以今后更新将主要基于篡改猴，其他的管理器并不能保证兼容性
