### ISSUE TITLE
标记点保存按钮没反应，但是能标记上

### ISSUE THREAD

**Issue by DelCrona** [kisshang1993/NGA-BBS-Script#88]
**描述错误信息**

标记点保存按钮没反应，但是能标记上

**复现步骤**
此问题的复现步骤:

标记列表字符串超过5M

**屏幕截图**
包含错误截图，F12控制台输出，配置设置信息等
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/aa43bbda-7631-4334-83d7-df3781f8f52f)

**浏览器及版本号**
例如:
 - chrome [122]
 - Edge

**脚本管理器及版本号**
例如:
 - Tampermonkey [5.0.6192]

**补充说明**

**Comment by kisshang1993** [comment]
已在v4.5.1中修复此问题
