### ISSUE TITLE
查看用户活动记录功能失效 

### ISSUE THREAD

**Issue by DelCrona** [kisshang1993/NGA-BBS-Script#90]
**描述错误信息**
点按钮的弹窗白屏转圈

**复现步骤**
此问题的复现步骤:
点击查看用户活动记录按钮

**屏幕截图**
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/68556d64-94f2-41fc-9fd8-0f647c65f4b3)
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/c415d390-8d8b-4ff8-9d20-032f90fa3591)

**浏览器及版本号**
 - Microsoft Edge 

**脚本管理器及版本号**
 - Tampermonkey [4.19.0]

**补充说明**
例如安装了其他插件，或者特殊的使用环境等

**Comment by golden2077** [comment]
+1，遇到同样的问题

**Comment by kisshang1993** [comment]
NGA数据接口添加了限流，故此4.5.2版本已做了相关处理
如查询过快触发了限流，只能等一会再重试
