### ISSUE TITLE
标记json字符串超过50M，本体和本体插件会失效

### ISSUE THREAD

**Issue by DelCrona** [kisshang1993/NGA-BBS-Script#94]
**描述错误信息**
标记json字符串超过50M，本体和本体插件会失效
**复现步骤**

刚过50M：本体+5个插件，
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/4be67361-c987-42b4-af55-cbea8a4f1b21)
这两个插件只能2选1开启，否则本体失效
继续合并上传20000标记（大概2M）：本体直接失效。

以40M数据为基底，合并上传16M的文件：提示上传成功但是未合并，数据无变化。

**屏幕截图**
插件失效，并无控制台报错

**浏览器及版本号**
例如:
 - Microsoft Edge 
 - Chrome

**脚本管理器及版本号**
例如:
 - Tampermonkey [5.0.1]

**补充说明**
推测是基于篡改猴存储的数据不能超过50M?

**Comment by kisshang1993** [comment]
50M的数据量也忒大了点...
油猴储存底层用的leveldb，设计上是没有储存限制的，再观察下插件失效时有无报错提示？

**Comment by DelCrona** [comment]
> 50M的数据量也忒大了点... 油猴储存底层用的leveldb，设计上是没有储存限制的，再观察下插件失效时有无报错提示？
观察之后出现了点新的问题
![PDXEL)CB_7BG}8UYIANPJUV](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/c7ce4ac8-6817-448c-81fd-864b0bf6e050)
应该是在执行_this.mainScript.setValue("hld__NGA_mark_list", markListStr);的时候报错
合并上传的结果是可以正常导出的，在合并之后，setValue之前，有一次写入markandban模块 marklist变量的操作 _this.mainScript.getModule('MarkAndBan').markList = markList;
上传之后直接导出也是读取的这个变量，说明出问题的是setValue，看报错好像是标记字符串太长了

此外 直接上传或合并结果55M的时候跳上文超过最长限制的报错，但是插件本体正常
50-55M之间的时候还是原来插件完全失效的问题，没有报错，就好像插件没有加载一样

最后是新的问题，疑似是greasyfork.org的问题，今天在复现的时候重装插件之后就这样了
![image](https://github.com/kisshang1993/NGA-BBS-Script/assets/44667271/40da5c9c-01ce-432a-ac87-860320d59ff5)
读不了样式文件 不知道是我本身ip的问题还是网站的问题

**Comment by DelCrona** [comment]
> 50M的数据量也忒大了点... 油猴储存底层用的leveldb，设计上是没有储存限制的，再观察下插件失效时有无报错提示？

多合了几个文件做了下测试

插件：本体+备份 上传51.7M：正常；52.2M-53M 崩（无报错）；54.3M：过长报错
插件：本体+5个扩展模块 50.3M及以上：崩（无报错）；54.3M：过长报错 
跟原来差不多的推测：加插件同时，本体配置文件会增加；配置文件+标记字符串这个存储不能超过54.3M（更精确的值测不动了）
用GM写入过长的值就会禁止写入报错；写入没有超长的值，但是写入后超长的话就会把其他配置文件顶掉，所以插件跑不起来，自然也没有报错。
那好像也没什么办法..（除非油猴更新？我也不太懂油猴，插件都是摸索着瞎写的，也可能是其他因素，总之超长报错这个东西确实是客观存在的

**Comment by kisshang1993** [comment]
初步判断可能是保存超长字符串时出了问题
我提交了个分支[v4.5.3-beta](https://github.com/kisshang1993/NGA-BBS-Script/tree/v4.5.3-beta) 实现了切片保存功能，每10M切一次，你可以先测试一下是否能解决这个问题

**Comment by DelCrona** [comment]
> 初步判断可能是保存超长字符串时出了问题 我提交了个分支[v4.5.3-beta](https://github.com/kisshang1993/NGA-BBS-Script/tree/v4.5.3-beta) 实现了切片保存功能，每10M切一次，你可以先测试一下是否能解决这个问题
> 
> 记得备份数据

测了，没出新的问题，超长报错没了，但是超过上面的大小插件还是不工作也没有报错。

**Comment by DelCrona** [comment]
做了一些测试，感觉可以锤了是容量问题了：
在本体初始化script和script.run中间插了几个断点，存储正常的时候，断点会在初始化前面正常输出，存储不正常的时候断点没有输出，插件压根没跑起来；
把标记字符串额外写入4次存储："hld__NGA_mark_list_2-5"
用16M 11M 10M 分别测试 前两个毫不意外的崩了（80M，55M）
在本体并不读取2-5的情况下，看上去应该是油猴本身的问题了

**Comment by kisshang1993** [comment]
可以使用 `// @require      file://D:/PATH`   来访问本地文件，需要设置允许油猴访问本地文件地址，这样基本也就只能自己使用了

**Comment by kisshang1993** [comment]
另外有种思路就是通过indexdb来实现储存标记名单，理论上储存数据无上限，但改动量稍微有点大...
