### ISSUE TITLE
用户活跃板块记录-深度统计时，从发布主题第二页开始出现HTTP 503错误

### ISSUE THREAD

**Issue by XeonStin** [kisshang1993/NGA-BBS-Script#98]
**描述错误信息**
用户活跃板块记录-深度统计时，从发布主题第二页开始出现HTTP 503错误。
将查询间隔由2000ms修改为5000ms，或隔较长时间后重播XHR均无法解决。
但统计发布主题第一页与回复主题第一页均无问题，且在浏览器地址栏直接输入请求URL`https://nga.178.com/thread.php?__output=11&authorid=脱敏&page=2`并访问可以得到正常json数据。

**复现步骤**
此问题的复现步骤:
1. 打开任意帖子
2. 点击用户信息下的“查看用户活动记录”按钮
3. 点击用户活跃板块记录面板上的“深度统计”按钮

**屏幕截图**
插件弹窗显示`查询【发布主题第2页】数据接口失败! 原因: 服务器HTTP返回:503`
控制台显示`GET https://nga.178.com/thread.php?__output=11&authorid=脱敏&page=2 503 (Service Unavailable)`

**浏览器及版本号**
Microsoft Edge [126.0.2592.56]

**脚本管理器及版本号**
Tampermonkey [5.1.1]

**补充说明**
关闭其他插件、脚本仍然能复现该问题

**Comment by repokx** [comment]
貌似是nga限制了插件查成分的范围？
https://greasyfork.org/zh-CN/scripts/492711-nga%E4%BC%98%E5%8C%96%E6%91%B8%E9%B1%BC%E4%BD%93%E9%AA%8C%E6%8F%92%E4%BB%B6-%E4%BF%A1%E6%81%AF%E5%8A%A0%E5%BC%BA

**Comment by kisshang1993** [comment]
之前是使用脚本查成分查的太猖狂了，NGA就开始对API进行风控了，请求过快是会503，或者HTTP错误，这个没有办法，只能降低查询速度/或多次累加查询
